workflows:
  expo-android:
    name: Build Expo Android App
    max_build_duration: 60
    environment:
      node: latest
    scripts:
      - name: Install dependencies
        script: npm install
      - name: Build Android app
        script: |
          npm install -g eas-cli
          eas build --platform android --profile preview --local --output build/
    artifacts:
      - build/*.apk
      - build/*.aab
    publishing:
      email:
        recipients:
          - princeevans379@gmail.com
