workflows:
  build_and_publish:
    name: Build and Publish
    environment:
      vars:
        EXPO_TOKEN: ct64QMiPUY18PXAz_kqrdLvWMyr05pmyWN9TV0zx
      node: latest
      flutter: stable
    scripts:
      - name: Install dependencies
        script: |
          npm install -g eas-cli
          npm install
      - name: Build Android app
        script: |
          eas build --platform android --non-interactive
    artifacts:
      - build/**/*
