workflows:
  expo-android:
    name: Build Expo Android App
    max_build_duration: 60
    environment:
      vars:
        EXPO_APP_NAME: "lesson01"
      node: latest
      expo: latest
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Build Android app
        script: |
          npx expo export --platform android --output-dir dist
    artifacts:
      - dist/**/*.apk
    publishing:
      email:
        recipients:
          - princeevans379@gmail.com
